In [1]:
import pandas as pd
import numpy as np
import re    # regular expression
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\JOEL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# Printing stopwords in english
print(stopwords.words("english"))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Data Processing

In [4]:
# Loading the data
df=pd.read_csv(r"C:\Users\JOEL\Downloads\twitter_analysis.csv",encoding="ISO-8859-1")

In [5]:
df.shape

(1599999, 6)

In [6]:
df.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [7]:
# Naming Columns
column_names=['target','id','date','flag','user','text']
df=pd.read_csv(r"C:\Users\JOEL\Downloads\twitter_analysis.csv",names=column_names,encoding="ISO-8859-1")
df.head()

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [8]:
# Checking for missing values
df.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

In [9]:
# Checking Distribution of targt column
df['target'].value_counts()

target
0    800000
4    800000
Name: count, dtype: int64

In [10]:
# Convert Target value 4 to 1
df.replace({'target':{4:1}},inplace=True)
df['target'].value_counts()

target
0    800000
1    800000
Name: count, dtype: int64

In [11]:
# 0--> Negative Tweet
# 1--> Positive Tweet

Stemming

In [11]:
port_stem=PorterStemmer()

In [12]:
def stemming(content):
    stemmed_content=re.sub('[^a-zA-Z]',' ',content)
    stemmed_content=stemmed_content.lower()
    stemmed_content=stemmed_content.split()
    stopword= set(stopwords.words('english'))
    stemmed_content= [port_stem.stem(word) for word in stemmed_content if not word in stopword]
    stemmed_content= ' '.join(stemmed_content)
    return stemmed_content

In [13]:
df['stemmed_content']=df['text'].apply(stemming)

In [14]:
df.head()

,target,id,date,flag,user,text,stemmed_content
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",switchfoot http twitpic com zl awww bummer sho...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,upset updat facebook text might cri result sch...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,kenichan dive mani time ball manag save rest g...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,whole bodi feel itchi like fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",nationwideclass behav mad see

In [16]:
print(df['stemmed_content'])

0          switchfoot http twitpic com zl awww bummer sho...
1          upset updat facebook text might cri result sch...
2          kenichan dive mani time ball manag save rest g...
3                            whole bodi feel itchi like fire
4                              nationwideclass behav mad see
                                 ...
1599995                           woke school best feel ever
1599996    thewdb com cool hear old walt interview http b...
1599997                         readi mojo makeov ask detail
1599998    happi th birthday boo alll time tupac amaru sh...
1599999    happi charitytuesday thenspcc sparkschar speak...
Name: stemmed_content, Length: 1600000, dtype: object

In [17]:
print(df['target'])

0          0
1          0
2          0
3          0
4          0
          ..
1599995    1
1599996    1
1599997    1
1599998    1
1599999    1
Name: target, Length: 1600000, dtype: int64

In [19]:
# Seperating the data and label

x=df['stemmed_content'].values
y=df['target'].values

Splitting data into test data and train data

In [29]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,stratify=y,random_state=42)

Converting text data to numeric data

In [30]:
vectorizer= TfidfVectorizer()

x_train=vectorizer.fit_transform(x_train)
x_test=vectorizer.transform(x_test)

In [31]:
print(x_train,x_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9453607 stored elements and shape (1280000, 461280)>
  Coords	Values
  (0, 307108)	0.46206048815324474
  (0, 239679)	0.15130037108228483
  (0, 146067)	0.12929728405657018
  (0, 175252)	0.224070805470346
  (0, 128605)	0.22108856600702773
  (0, 4832)	0.317074267861159
  (0, 124524)	0.18318401951949756
  (0, 205794)	0.24140229063801746
  (0, 454381)	0.20169626473577715
  (0, 286478)	0.16123218610004272
  (0, 406297)	0.2978221095272138
  (0, 220296)	0.43015677907624866
  (0, 388138)	0.20555120011808467
  (0, 154767)	0.26976607043258233
  (1, 445870)	0.6361096685891185
  (1, 161801)	0.5778049407933611
  (1, 124611)	0.5113765148324884
  (2, 125319)	0.6383069130836649
  (2, 349409)	0.22232944888223494
  (2, 444761)	0.30331529032956345
  (2, 358186)	0.19837942712286838
  (2, 267649)	0.19309660201644555
  (2, 12436)	0.2529872032123258
  (2, 453420)	0.2347069337186747
  (2, 312657)	0.3154702974657607
  :	:
  (1279997, 124611)	0.2537781914144255
  (1279997, 301683)	0.1908678391932645
  (1279997, 168646)	0.20490659397970187
  (1279997, 156392)	0.23570311036994007
  (1279997, 151848)	0.18681351768822982
  (1279997, 259065)	0.26819595864353835
  (1279997, 394120)	0.24857410036759808
  (1279997, 372797)	0.3021907911926725
  (1279997, 262076)	0.3257051331036561
  (1279997, 80839)	0.4085075096529922
  (1279997, 120136)	0.5183864288132355
  (1279998, 329551)	0.3477852392627569
  (1279998, 71116)	0.26101247237184594
  (1279998, 49119)	0.24937088067546037
  (1279998, 115954)	0.24199212168201903
  (1279998, 442745)	0.46003281711454636
  (1279998, 138188)	0.22903437381896502
  (1279998, 33019)	0.5505296949726769
  (1279998, 225235)	0.3507164257239226
  (1279999, 169469)	0.24275491614294809
  (1279999, 104826)	0.39497658307784106
  (1279999, 388491)	0.3269499490733422
  (1279999, 118242)	0.3604832171863622
  (1279999, 349900)	0.3245817059299737
  (1279999, 267426)	0.6654816651208961 <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2288367 stored elements and shape (320000, 461280)>
  Coords	Values
  (0, 28874)	0.1778395103911245
  (0, 43712)	0.23562815302828183
  (0, 78636)	0.5158100011206617
  (0, 96399)	0.255967788489452
  (0, 97585)	0.4019235611854435
  (0, 129417)	0.25650960779862714
  (0, 189057)	0.31324918577405797
  (0, 240451)	0.15341308097014625
  (0, 334643)	0.14719329779308424
  (0, 335577)	0.22602158147814247
  (0, 384697)	0.3281164007446601
  (0, 435956)	0.14183025329879742
  (0, 453357)	0.1781708363247895
  (1, 35118)	0.3128685670821343
  (1, 36669)	0.2729958846742327
  (1, 39445)	0.16867093960211466
  (1, 57115)	0.19043301054662504
  (1, 74274)	0.21148120876702692
  (1, 78790)	0.13386322067407883
  (1, 170374)	0.17525273735418329
  (1, 171245)	0.12468774856570086
  (1, 183279)	0.24586158827112847
  (1, 233854)	0.3852709938491561
  (1, 240223)	0.1674195650536303
  (1, 301683)	0.13212235134015302
  :	:
  (319997, 135536)	0.21809964977532384
  (319997, 146067)	0.31485892246365776
  (319997, 169469)	0.1945044482645627
  (319997, 225096)	0.2933179603743362
  (319997, 376036)	0.2335941225019601
  (319997, 438565)	0.19669688299412047
  (319997, 443410)	0.20628884141115603
  (319998, 35323)	0.24243688403979866
  (319998, 95798)	0.31645368593596523
  (319998, 115954)	0.24587170807357303
  (319998, 127979)	0.24824116108565378
  (319998, 130270)	0.16408547784640734
  (319998, 150603)	0.3076966959712389
  (319998, 169469)	0.16828053521756142
  (319998, 227862)	0.17626972873530924
  (319998, 230521)	0.23127598680385447
  (319998, 234585)	0.14634570758159743
  (319998, 281884)	0.40416959301312766
  (319998, 368628)	0.22494548369604894
  (319998, 391857)	0.3533227149718125
  (319998, 436860)	0.2992074077395669
  (319998, 438120)	0.1865288234043992
  (319999, 56596)	0.4969436428888122
  (319999, 93851)	0.2958769159422991
  (319999, 337075)	0.8157842033312919

Training the Model

In [32]:
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

Model Evaluation

In [33]:
x_train_prediction= model.predict(x_train)
training_data_accuracy= accuracy_score(y_train,x_train_prediction)

In [34]:
print(f"Accuracy score on training data : {training_data_accuracy}")

Accuracy score on training data : 0.7999984375

In [35]:
x_test_prediction= model.predict(x_test)
test_data_accuracy= accuracy_score(y_test,x_test_prediction)
print(f"Accuracy score on test data : {test_data_accuracy}")

Accuracy score on test data : 0.776796875

Saving the trained model

In [36]:
import pickle

In [37]:
f='trained_model.sav'
pickle.dump(model,open(f,'wb'))

Using the saved model for future predictions

In [45]:
loaded_model= pickle.load(open('trained_model.sav','rb'))

In [51]:
x_new= x_test[3]
print(y_test[3])

prediction=model.predict(x_new)
print(prediction)

if prediction[0]==0:
    print("Negative Tweet")
else:
    print("Positive Tweet")

1
[1]
Positive Tweet